### ISSUE TITLE
使用正则或其他对event匹配

### ISSUE THREAD

**Issue by niuhuan** [niuhuan/rust_proc_qq#17]
参考 [SimpleBot](https://github.com/LovesAsuna/SimpleBot)

```rust

// 场景一
// 解析命令
#[event(command("hello {name}"))]
async fn hello(event: &MessageEvent, name: Option<String>) -> anyhow::Result<bool> {
    if name.is_none() {
        return Ok(false);
    }
    event.send_message_to_source(format!("hello {}", name.unwrap()).parse_message_chain()).await.unwrap();
    Ok(true)
}

// 场景二
// 解析且必须通过过滤器，例如游戏，判断有没有redis状态机
#[event(all(command("hello {name}", filter = "i_am_filter")))]
async fn hello(event: &MessageEvent) -> anyhow::Result<bool> {
    if name.is_none() {
        return Ok(false);
    }
    event.send_message_to_source(format!("hello {}", name.unwrap()).parse_message_chain()).await.unwrap();
    Ok(true)
}

async fn filter(event: &MessageEvent) -> anyhow::Result<bool> {
    if name.is_none() {
        return Ok(false);
    }
    event.send_message_to_source(format!("hello {}", name.unwrap()).parse_message_chain()).await.unwrap();
    Ok(true)
}

// 场景3 消息必须符合正则表达式
#[event(regexp("hello {name}"))]

```

**Comment by niuhuan** [comment]
我觉得可以 @LovesAsuna ， 你得想法非常棒 (๑•̀ㅂ•́)و✧

**Comment by niuhuan** [comment]
这块我不知道怎么获取event里面方法，例如 `#[event(command("hello {name}"))]`  `#[event(all(command("hello {name}", filter = "i_am_filter")))]` 。

 @LovesAsuna

我没有看懂你写的代码。

**Comment by LovesAsuna** [comment]
什么叫获取event里面的方法？

**Comment by niuhuan** [comment]
从 `#[event(command("hello {name}"))]` 获取到 `command("hello {name}")` 并解析

**Comment by LovesAsuna** [comment]
我的宏里面的格式`#[action("hello {name}")]`，所以代码是
```rust
let look_head = input.lookahead1();
if look_head.peek(syn::LitStr) {
    let lit_str = input.parse::<syn::LitStr>().unwrap();
    let pattern = lit_str.value();
    let stream = pattern.parse::<TokenStream>().unwrap();
    let args = syn::parse::<Arg>(stream)
    .map(|args| {
        args.clone()
        .into_iter()
        .enumerate()
        .collect::<HashMap<_, _>>()
    })
    .ok()
    .unwrap_or(HashMap::new());
    Ok(Meta { pattern, args })
}
```

这里`lookhead1`把解析流推进了一步，这是个隐式操作，并不知道推进到什么地步。然后下面对这个推进的内容进行一次判断，由于我这里只是用了简单的字符串字面量，所以是用`peek(LitSstr)`判断获取到的是不是一个字符串字面量。符合的话通过value就可以拿到值了，就是`hello {name}`

---

如果你要写成`#[event(command("hello {name}"))]`，那里面的内容就是`command("hello {name}")`了，处理起来可能会有点复杂，在这里command什么都不是，我觉得当成Ident处理会比较适合，拿到值之后判断是不是command就好了，然会匹配一次左括号，一次字符串字面量，一次右括号，把过程封装起来就好了(**猜测写法，不一定是这么写的，尤其是`Idennt`不确定这里是不是要用这个**)

**Comment by niuhuan** [comment]
syn::AttributeArgs 看起来很可行

:construction: :construction: :construction: :construction: :construction: 
https://github.com/niuhuan/rust_proc_qq/blob/f950dc679501cdcebe78211c12a714260f82010b/proc_qq_codegen/src/lib.rs#L75

**Comment by LovesAsuna** [comment]
https://github.com/niuhuan/rust_proc_qq/blob/f950dc679501cdcebe78211c12a714260f82010b/proc_qq_codegen/src/lib.rs#L220
这一行是不是要单独放在impl里的？这样子是可以过编译的嘛？

**Comment by niuhuan** [comment]
> https://github.com/niuhuan/rust_proc_qq/blob/f950dc679501cdcebe78211c12a714260f82010b/proc_qq_codegen/src/lib.rs#L220
> 
> 
> 这一行是不是要单独放在impl里的？这样子是可以过编译的嘛？

你说的对 o((>ω< ))o 啊啊啊啊，我再改改，没有放参数的时候编译过了

**Comment by niuhuan** [comment]
#19 

any , all ,  not, trim_regexp , trim_eq,  regexp, eq 写完了

filter还没有写。看着像是有生命周期问题，需要再弄一个宏变成trait。

**Comment by LovesAsuna** [comment]
参数注入这个功能好像还没有实现，现在只有raw的

**Comment by niuhuan** [comment]
我觉得参数注入这个可能需要改变函数的参数个数（加一个map或者多个参数），或者生成一些代码在#block里。再弄个macro!提取。

**Comment by LovesAsuna** [comment]
我的做法就是加了一个map，要解决的问题就是编译时和运行时的交互，这部分我没什么好的想法，我是直接用json硬编码在代码里了，虽然很丑陋但是起码能用o((>ω< ))o

**Comment by LovesAsuna** [comment]
看了下代码，限制参数顺序一致确实好写多了，不用考虑很多奇怪的情况。然后参数的类型是不是可以扩展到支持`ricq_core::msg::elem::RQElem`?
(另外我还挺好奇现在是怎么测试的，tlv544直接让机器人跑不起来)

**Comment by niuhuan** [comment]
> 看了下代码，限制参数顺序一致确实好写多了，不用考虑很多奇怪的情况。
> 
> > 然后参数的类型是不是可以扩展到支持`ricq_core::msg::elem::RQElem`?
> > (另外我还挺好奇现在是怎么测试的，tlv544直接让机器人跑不起来)

我用的之前的session恢复登录测试的。


不过我本地cargo clean之后也编译不过了。改了一下依赖才编译过 https://github.com/niuhuan/rust_proc_qq/commit/a33f2db44042f4659bd5dfcc27db56491a1840d2

**Comment by niuhuan** [comment]
匹配了一些类型 cargo check 通过了, 我还没测是不是能用

`ricq_core::msg::elem::RQElem` 应该也可以，你是想匹配@At么？

**Comment by LovesAsuna** [comment]
对，匹配at的对象是挺常用的。就处理几个常用的RQElem就好了

**Comment by niuhuan** [comment]
> ricq_core::msg::elem::RQElem

还有可能会@多个人，得到一个 Vec<At> 🙂

这样我现在代码里的参数，也许这里需要改成迭代器

https://github.com/niuhuan/rust_proc_qq/blob/5387f3bcb51cb88b11230417009afc439220595f/proc_qq_codegen/src/lib.rs#L382

我想我们可以把 RQElem::序列化成一些特殊的字符串，例如`[RICQ::AT("i64,base64")]` 之后再去匹配。减小部分难度。

**Comment by niuhuan** [comment]
已经支持@了，可以试一试，我只自测了几个demo。examples里有demo。

https://github.com/niuhuan/rust_proc_qq/pull/26

**Comment by niuhuan** [comment]
已经支持各种 RQElem::* 枚举， 并且支持了自定义类型的解析

**Comment by LovesAsuna** [comment]
想迁移命令，突然发现命令缺少一个次要命令。就是
![T1F@8TN2KJK}HW2CZ@NT 3U](https://user-images.githubusercontent.com/32810896/231930467-a580c666-7348-46bd-aa04-35a1fadbc36d.png)

**Comment by niuhuan** [comment]
hhhh 阔以搞一下。暂时先用参数代替第二个命令吧。

**Comment by LovesAsuna** [comment]
又发现还有这种命令了😂，
![63 5$ 0P%CX@ _9OG8~G1`Q](https://user-images.githubusercontent.com/32810896/233358098-fc4b279a-4807-47d9-b096-e4dc39847b62.png)，这种我要怎么迁移？

**Comment by niuhuan** [comment]
你可以看看源代码我现在是怎么处理的。我觉得可以给枚举加上标识符是否算匹配。

**Comment by niuhuan** [comment]
已经在写了，脑子快被烧光了。而且我把rust升到最新版就没办法编译了。/(ㄒoㄒ)/~~。

https://github.com/niuhuan/rust_proc_qq/blob/b5f479fd4ade62cdfdcb306c35da9ec666d1417f/proc_qq/src/handler/mod.rs#L624

**Comment by LovesAsuna** [comment]
对，我也发现了，新的nightly加了一些限制，然后ricq过不了编译

**Comment by LovesAsuna** [comment]
感觉有没有空格切割都差不多，都是一样的算法

**Comment by niuhuan** [comment]
> 感觉有没有空格切割都差不多，都是一样的算法
连续匹配两个数字没有空格分隔的话不知道前后顺序

**Comment by niuhuan** [comment]
你可以试试  proc_qq = { git = "", branch = "sub_command" } ， 大概意思写完了

**Comment by LovesAsuna** [comment]
越来越复杂了，要看不懂了🤣

**Comment by niuhuan** [comment]
> 改进了一版本，推到sub_command分支了，感觉还不错。会把 {param1}ABC{param2} 看成一个整体去匹配。棒棒，不过没有测试效果。用git引入得ricq，不需要降低rust版本

挺简单的，就是先按照空格切。然后再切开子元素。

**Comment by niuhuan** [comment]
你看看能用不

**Comment by LovesAsuna** [comment]
我只能测试能不能编译，实际效果没法测。ricq一直没有弄tlv544，我的机器人一直是没法登录

**Comment by rcoplo** [comment]
代码是:
![image](https://user-images.githubusercontent.com/83597965/234231391-ec0a62db-8319-4e57-a049-55554474c334.png)
实际匹配到的是这样的
![image](https://user-images.githubusercontent.com/83597965/234231528-ad299ea9-74af-45fa-87a6-b58e96d0de5c.png)

**Comment by rcoplo** [comment]
还有,如果指令是:
```
/test5秒后发送ok
```
会报错
```
 panicked at 'byte index 11 is not a char boundary; it is inside '后' (bytes 9..12) of `/test5秒后发送ok`
```

**Comment by niuhuan** [comment]
好的 🌹

**Comment by niuhuan** [comment]
上面的panic是我切字的时候切错了。协议问题只能等ricq维护，QQ的协议我一点也搞不懂。

**Comment by LovesAsuna** [comment]
匹配这部分太复杂了，没有debug太难理解了。如果有mock的单元测试可以辅助debug来理解就好了。
然后有好多`multi`写成了`mutil`

**Comment by niuhuan** [comment]
> 匹配这部分太复杂了，multi_matcher看不懂，没有debug太难理解了。如果有mock的单元测试可以辅助debug来理解就好了。 然后有好多`multi`写成了`mutil`


我应该改单词错了嘛，我换个词

**Comment by niuhuan** [comment]
我测了最后提交的代码里，中文会出现问题，英文不会。

thread 'tokio-runtime-worker' panicked at '`byte` index 11 is not a `char` boundary; it is inside '后' (bytes 9..12) of `/test5秒后发送ok`', proc_qq\src\handler\mod.rs:604:36

是个头疼的问题

**Comment by niuhuan** [comment]
好了，我已经测通过了

```rust
// 匹配子命令2
#[event(bot_command = "/test{var1}秒后发送{var2}")]
async fn handle10(_message: &MessageEvent, var1: i64, var2: String) -> anyhow::Result<bool> {
    println!("handle10。 : {:?} , {:?} ", var1, var2);
    Ok(true)
}
```

```
/test5秒后发送ok
``

```
handle10。 : 5 , "ok"
```

**Comment by LovesAsuna** [comment]
要不要弄一个mock单测

**Comment by niuhuan** [comment]
> 要不要弄一个mock单测

message里面还有client。数据太过复杂。我并不知道怎么才能弄一个mock的mod出来。
如果你在尝试读我写的代码，可以PR点备注或者README进来。

**Comment by LovesAsuna** [comment]
再抽象出一个新的trait，让mock和ricq分别实现它，单测的时候用这个trait

**Comment by niuhuan** [comment]
https://github.com/niuhuan/rijq
