### ISSUE TITLE
能提供个部署方案吗，比如docker

### ISSUE THREAD

**Issue by coWhy** [niuhuan/rust_proc_qq#22]
发现自己并不是太了解如何部署可执行程序

**Comment by niuhuan** [comment]
我简单说下docker。

0. 编译，参考example， 首先你要用一个ubuntu系统将他编译，并运行 当然你可以用debian，选择docker镜像时要使用相同镜像避免依赖版本不一致。如果你用ubuntu20.04.4, 那么你用的docker镜像就是 ubuntu:20.04.

1. 尝试运行一个二进制程序在docker，
   1). 运行一个docker `docker run -d -name ubuntu -itd /bin/bash ubuntu:20.04` , 这样你就有了自己的docker镜像并且在运行
   2). 你可以把你的程序和配置文件里，比如叫 myqq 复制到docker里， `docker cp myqq ubuntu:`
   3). 运行你的文件，并尝试安装缺失的库 `./myqq`  最重要的是 libssl-dev

2. 制作装好依赖的ubuntu
    docker build -t ubuntu:certs .
    ```Dockerfile
    FROM ubuntu:20.04
    RUN apt-get -qq update \
      && apt-get -qq install -y --no-install-recommends ca-certificates curl  libssl-dev openssl
    ```

3. 把自己的配置文件放在/opt/myqq下 完整路径为 /opt/myqq/myqq, 运行docker，如果您想第一次运行docker的时候可以使用命令行，请加上参数 -it 不要加 -d。您可以仔细查我这个命令行的意思. `docker run --net host --name myqq --workdir=/app -v  /opt/myqq  -d ubuntu:certs ./myqq`

4.  您要知道 docker的一些参数  --restart -v -p 等
