### ISSUE TITLE
bot_command 功能设为 feature？

### ISSUE THREAD

**Issue by RogenDong** [niuhuan/rust_proc_qq#34]

**Comment by niuhuan** [comment]
我认为这很合理，并不是每个人都会用到bot_command。

**Comment by niuhuan** [comment]
我将event的args设置成了future。即便我没有经常使用它，它对性能的影响很小，以及仅仅增加几kb的体积，所以我暂时将他设置成了default-features

https://github.com/niuhuan/rust_proc_qq/pull/36

**Comment by RogenDong** [comment]
效率好高！
