### ISSUE TITLE
[功能] 定时任务支持

### ISSUE THREAD

**Issue by rcoplo** [niuhuan/rust_proc_qq#35]
大佬看看这个可行吗 [commit](https://github.com/rcoplo/rust_proc_qq/commit/e637217d348aabfc1fbd589f977b8cd2ed2c0d0b)
```rust
/// 每1分钟获取一次 bot uin
#[scheduler_job(cron = "0 0/1 * * * ?")]
async fn handle_scheduler(c:Arc<Client>) {
    let bot_uin = c.bot_uin().await;
    println!("{}", bot_uin);
}

/// scheduler
pub fn scheduler() -> SchedulerJob {
    scheduler!(
        "hello_jobs",
        handle_scheduler
    )
}
```
如果可以的话我提一个pr

**Comment by niuhuan** [comment]
这是个很好的提议。建议和module类似可以直接设置并使用。我很乐意接收这个想法。

需要注意以下。我刚提了一个PR，改动比较大。https://github.com/niuhuan/rust_proc_qq/pull/36

**Comment by niuhuan** [comment]
如果可以的话merge以下master之后进行PR。

**Comment by rcoplo** [comment]
> 如果可以的话merge以下master之后进行PR。

好的

**Comment by niuhuan** [comment]
我先尝试改一下你的代码，比如
 -  `jobs_scheduler` 放在client里面，不需要建立多个。
 - 让handler返回result，这样用起来方便一起
 - 或者在`clientBuilder::build`的时候就执行一些init的动作，而不是推迟到run。

**Comment by rcoplo** [comment]
> 我先尝试改一下你的代码，比如
> 
> * `jobs_scheduler` 放在client里面，不需要建立多个。
> * 让handler返回result，这样用起来方便一起
> * 或者在`clientBuilder::build`的时候就执行一些init的动作，而不是推迟到run。
> 
> 遇到问题我会推送到dev给你看一下

好

**Comment by niuhuan** [comment]
我发现 `JobScheduler::start().await` 返回的是 `()`. 我怎么才能shutdown? 并且等他所有job执行完？

**Comment by niuhuan** [comment]
https://github.com/niuhuan/rust_proc_qq/commit/4d211002624a5c12f3b693a8b4b10a3546ba26f6

我把我刚才的想法加了进去，我只改了 proc_qq 没有改 codegen.

jobs_scheduler.start() 这个名字我看你用`tokio::spawn`调用，start看起来是启动的意思。

**Comment by niuhuan** [comment]
我的想法是一开始就设置好任务，然后一起启停，

https://github.com/niuhuan/rust_proc_qq/blob/4d211002624a5c12f3b693a8b4b10a3546ba26f6/proc_qq/src/features/scheduler.rs#L1

**Comment by rcoplo** [comment]
我试了一下,当`shutdown()` 之后,再次`start()`就会报错了,`JobScheduler` 需要重新初始化,添加任务才行

**Comment by niuhuan** [comment]
> 我试了一下,当`shutdown()` 之后,再次`start()`就会报错了,`JobScheduler` 需要重新初始化,添加任务才行

我改一下

**Comment by niuhuan** [comment]
改好了

**Comment by rcoplo** [comment]
没问题了,可以加个`Module`和`Scheduler`添加的时候的日志吗

**Comment by niuhuan** [comment]
调用的时候？文档还需要改一改

**Comment by niuhuan** [comment]
> > 调用的时候？我写todo的时候吗？文档还需要改一改
> 
> [这种](https://github.com/rcoplo/rust_proc_qq/blob/13861df497764b23672fb2e40229463f727e1d01/proc_qq/src/handler/scheduler.rs#L47) 加了日志好观察模块是否加载.

我把我的定时任务的代码提交到master了。增加了在编译时校验cron是否正确。

`builder::build`里面加上`tracing::debug`?    如果是的话，你可以pr一下。

**Comment by niuhuan** [comment]
贡献者里没有你，应该是rebase merge的问题。
