### ISSUE TITLE
[功能]bot_command模糊匹配帮助

### ISSUE THREAD

**Issue by LovesAsuna** [niuhuan/rust_proc_qq#40]
命令类型不匹配或者前缀部分匹配时推测出用户想要输入的命令并给出提示

**Comment by niuhuan** [comment]
细说一下标题

**Comment by LovesAsuna** [comment]
加上了

**Comment by niuhuan** [comment]
这个需求可以用 String , Vec<String> 实现。

**Comment by niuhuan** [comment]
我觉得可以把 event_params 单独写一个文档说明一下。README.md 里面留下 bot_command 和 trim_eq 然后链接过去

**Comment by niuhuan** [comment]
你晓不晓得 rust 当关键字输入错误时使用什么关键字？ 或者类似git clone 写成 clon 的时候是怎么推测出 clone的，rust有没有类似的库？

**Comment by LovesAsuna** [comment]
关键字输入错误是啥意思？推测的话计算一下字符串相似度？或者改一改kmp算法得状态机

**Comment by LovesAsuna** [comment]
不知道这个可不可以https://github.com/lotabout/fuzzy-matcher
