### ISSUE TITLE
恢复会话失败回调

### ISSUE THREAD

**Issue by mosttt** [niuhuan/rust_proc_qq#41]
能否提供一个重新登陆失败的回调接口，方便失败之后做一些操作，例如重启自身来登录。

**Comment by niuhuan** [comment]
默认是掉线自动去重新登录的，也可以用run_once接口只循环一次，离线后函数会运行结束出栈。

有登录事件（但是不一定会登录成功）和离线事件。

**Comment by niuhuan** [comment]
您也可以看一下run的代码，描述一下您想在哪里加些什么。

**Comment by mosttt** [comment]
![LJZ@DIYH9X98XP%I((Q6R44](https://github.com/niuhuan/rust_proc_qq/assets/33774040/492f7c87-4c7c-41a3-bac4-3cde8e283ab2)
这段是我自己加的，想在这里加一个回调。便于在返回错误程序关闭前做一些事情

**Comment by niuhuan** [comment]
这个Event？`ConnectedAndOnlineEvent`

**Comment by niuhuan** [comment]
它是在loop_events开始的时候发送的

**Comment by mosttt** [comment]
我的意思是重新登录失败，退出loop并且抛出错误之前提供一个接口。
  一般这种情况下错误直接抛到了main方法上，软件即将panic，我想在此之前提供一个接口，就可以用代码重启一个新的。（二维码登录的情况下，恢复会话会大概率失败，直接重启软件能成功登录）。不知道我描述的清楚嘛

**Comment by mosttt** [comment]
并且在这个回调下，我也可以使用一些通知服务来提醒我机器人恢复会话失败，挂了。
直接在run_clien()下lf let Err的话处理起来不太方便。

**Comment by niuhuan** [comment]
离线的时候会有 `DisconnectedAndOfflineEvent ` 事件

**Comment by niuhuan** [comment]
loop_events 只有几行代码好像，专门就是做这个的

**Comment by mosttt** [comment]
好的 感谢 我去看看
